### ISSUE TITLE
sharing link does not work

### ISSUE THREAD

**Issue by eleaner** [mickael-kerjean/filestash#111]
Hi,

I connected nuage to my minio and tried to access the sharing link from a different browser.
It does not seem to work and I believe it's because I am actually logged to minio only in the first session. My nuage installation does not have a clue how to connect to my minio on its own.

Do I do something wrong or is it not yet implemented?
Unless I should configure my nuage - but here is another issue, how do I configure my installation in the docker? The wiki does not explain that.

Thanks
Marcin

**Comment by mickael-kerjean** [comment]
Hello,

> Do I do something wrong or is it not yet implemented?

The feature is very experimental and work in progress at this stage. I managed to get it working when it comes to share folders (no file yet). Can't you make it work with folders?

> Unless I should configure my nuage

At this point the configuration is still WIP but to be sure it doesn't come from a config issue and to be up with future releases you can add this to your config.json:
```
 {
   ....
   "share": {
        "enable": true,
        "groups": {
            "admin": "email@mail.com"
        }
    },
    "email": {
        "server": "smtp.gmail.com",
        "port": 587,
        "username": "username@gmail.com",
        "password": "passsowrd",
        "from": "username@gmail.com"
    },
.....
}
```
It's still WIP so not everything is working alright but the idea is:
- enable or disable the share feature
- create groups of people you can share with (let's say *@domain.com for everyone using an email address on a domain you control)
- smtp details: you need that if you restrict a link to certain people known by their email address. The idea is if someone tries to connect, he will receive a verification code by email. I got it working from my end but again it's very alpha quality at this point

**Comment by eleaner** [comment]
Thanks for the answer. 
yes I tried to share folder not a file but reading your answer  I still wonder how nuage would authenticate with the s3 backend when present with the share URL?

I also wonder how can I change the config json that is inside of the docker?

**Comment by mickael-kerjean** [comment]
> yes I tried to share folder not a file but reading your answer

That's interesting, I got it all fine from my end. Can you send me some credentials of your minio instance for me to investigate?

>  I still wonder how nuage would authenticate with the s3 backend when present with the share URL?

Well there's 2 side of things:
- When someone creates a share URL: nuage push the data in a sqlite db (that's the db.sql file that's store under ./data). This data contains among other thing your session data.
- When someone tries to access the share: nuage finds out the restrictions on your link and send some challenges (password restriction or/and email verification). If the user is allowed in, nuage reuse the session data that was used to create the share link.

In theory it's simple, in practise there's a lot of things to make sure everything is working nicely and securely, that's why the feature is still considered alpha and still a WIP at that point.

> I also wonder how can I change the config json that is inside of the docker?

You got to connect inside the docker instance and change it manually but if you're using docker everything should be working all fine without having to do that

**Comment by eleaner** [comment]
https://play.minio.io:9000/
Q3AM3UQ867SPQQA43P2F
zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

It is a hosted Minio server for testing and development purpose.
https://docs.minio.io/docs/minio-client-complete-guide

p.s.
I am having the same issue on your hosted nuage

**Comment by mickael-kerjean** [comment]
Hoo I didn't know minio had a demo, this is awesome!
I will give it a look when I got some more time. I'll keep you update in here

**Comment by eleaner** [comment]
could I start nuage in docker, somehow mapping the database folder to the
host folder?
and maybe the config too?

I would love to have a chance for them to stay persistent if I rebuild the
container
e.g. after your correction

**Comment by mickael-kerjean** [comment]
Yes of course. You'd need to add this to your docker-compose.yml:
```
nuage:
  image: machines/nuage
  ...
  volumes:
    - ./data/config/config.json:/app/data/config/config.json
```

Then you need to create the corresponding structure on your host:
```
mkdir -p ./data/config
curl https://raw.githubusercontent.com/mickael-kerjean/nuage/master/config/config.json > ./data/config/config.json
```
*Disclaimer*: I haven't test those commands yet

**Comment by eleaner** [comment]
looks like volumes mapping is working - awesome!!!!
    volumes:
    - ./data/config/config.json:/app/data/config/config.json
    - ./data/db.sql:/app/data/db.sql

would this be enough to make the config and sharing persistent?
now waiting for the minio sharing to start working

by the way, it would be double awesome if sftp could work without pass but with keys instead, though I have no idea how this could work in a browser.

**Comment by mickael-kerjean** [comment]
Just push some new code in there, It's not 100% complete. Example: https://nuage.kerjean.me/s/github_minio (password is "github")

**Comment by mickael-kerjean** [comment]
I got pretty much everything ready for prime time. 

Links can:
- have an expiration date
- have a custom url instead of an uggly random suite of characters
- have some access right attached
- be password protected
- be accessible only by certain people (by sending a verification code to the email you want to send) or even certain domain (let's say *@gmail.com would provide access to anybody's having a gmail account)
- be reshare if needed
- be created either for folders or files
- not be tampered with

The only missing bit is the webdav server (the same link will be usable both from a browser and/or network drive). 

Example on Minio:
- [shared folder](https://nuage.kerjean.me/s/github_minio): https://nuage.kerjean.me/s/github_minio => password is github
- [shared file](https://nuage.kerjean.me/s/1MheafS): https://nuage.kerjean.me/s/1MheafS

**Comment by eleaner** [comment]
this is seriously awesome!

**Comment by rikroe** [comment]
Hi,

I'm having the same issue with data being retrieved from SFTP. I've even set up a small local minio instance and have the same problem. 
Error message is either _Oops! Unkown Path_ for folders or _Can't load this picture_ for files/images.

I'm using your docker-compose file, i.e. the latest machines/nuage image.

Thanks for all your effort!

**Comment by mickael-kerjean** [comment]
I have a reproduction from my end, will investigate

**Comment by mickael-kerjean** [comment]
The sharing feature is bleeding edge at this point. The weird part is it doesn't work at all anymore. Moral of the story, to avoid such regression, I'm writing some integration tests

**Comment by mickael-kerjean** [comment]
You should be ready to rock. Some tests got written and the feature is working. Any issue from now on will be considered as a bug
