### ISSUE TITLE
Outliner mode for org files

### ISSUE THREAD

**Issue by Victor239** [mickael-kerjean/filestash#129]
I use [Orgzly](https://github.com/orgzly/orgzly-android) to edit org files on Android and I much prefer their UI for editing files:
![](https://lh3.googleusercontent.com/wpgcrjMLir6AAYo7HvXd5eca0HMDHtqaXt25BKbjHMBYBTSN0rTliql5nJDpFiNOY9PW=w1103-h658)

It would be great to have a similar UI option for Filestash.

**Comment by mickael-kerjean** [comment]
They are already different screen for todo and agendas:
![image](https://user-images.githubusercontent.com/13233076/52187855-d2902680-2883-11e9-815b-2676e5477860.png)

I'm not sure how it can be improve, feel free to share concrete ideas as I don't have any Android device around me these days.

**Comment by AWalton** [comment]
Sure, there's quite a few differences an outliner mode would have:
1) Can show more than 2 hierarchical levels e.g:
- a
  - b
    - c
      - d

2) Can [narrow](https://www.gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html) to zoom in to a particular note level, and use breadcrumbs or keyboard shortcuts to zoom out [(see example)](https://imgur.com/a/ki8ildW)

3) Can easily reorder notes and change identation level [(see example)](https://imgur.com/a/W6kYeZk)

Compared to the standard Org-mode view this looks and feels better for note-taking, plus the touch reordering, indenting and narrowing can't otherwise be done on mobile easily.

**Comment by mickael-kerjean** [comment]
The idea is brilliant. Also, does this already exist somewhere? Where did you got your screenshot from?

**Comment by AWalton** [comment]
The examples are from a non-orgmode outliner called WorkFlowy, and they have a web app you can [try here](https://workflowy.com/demo/embed/) (note: this page only works on desktop for some reason). Glad to help, if you need a beta tester let me know :)

**Comment by alaq** [comment]
I agree with @AWalton. This is probably the feature from workflowy I miss the most. In emacs, I'm sort of able to replicate it with `org-narrow-to-subtree`, and `widen`.

I would love for this to end up in Filestash.

**Comment by Victor239** [comment]
@mickael-kerjean is it possible to reopen this feature request?
