### ISSUE TITLE
[Feature Request] Plugin DIrectory

### ISSUE THREAD

**Issue by colin-streicher** [mickael-kerjean/filestash#138]
I realize this seems a bit ephemeral, but I was trying to run filestash and I was running into some issues and was looking for some plugins to help, though there are simple directions on creating a plugin, they are not too useful unless you read the source code. 
But if someone else has created something, I would prefer to use that. Conversely, if I write a useful plugin, it would be nice to advertise it to others who might be interested.

So I'm asking for two things, the primary one is a list of known plugins, endorsed by you or not. The second one is more indepth documentation on writing plugins. I am going to work on the documentation bit since I'm going through the code to get what I need anyways. But I think the plugin directory is a higher level thing for you to decide how or if you want to do it.

**Comment by mickael-kerjean** [comment]
> though there are simple directions on creating a plugin, they are not too useful unless you read the source code

You're right, at this point I didn't spend much effort documenting this aspect as I didn't receive much interests even though from where I sit, the hackability aspect is the most fun aspect of the project. I've submit a talk to the golang meetup hoping that could make a fun introduction to it.

> So I'm asking for two things, the primary one is a list of known plugins, endorsed by you or not.

The current list of plugin I've made is available here: https://github.com/mickael-kerjean/filestash/tree/master/server/plugin:
- plg_backend_dav: a caldav and cardav backend that I've tested with my selfhosted Radicale server (as I couldn't find a caldav frontend I was happy enough with)
- plg_backend_ldap: a ldap backend from which user can easily manage a LDAP directory (as I was trying to find an alternative to my PHPLDAPAdmin considering this project is dead, not maintained and became totally broken with the latest update of PHP and apache)
- plg_image_light: the plugin that's responsible for image transcoding of RAW images and image resizing. This plugin can be tricky to install as it requires some external libraries to be installed in the system (libvips and libraw)
- plg_image_heavy: this one is just about image resizing. Compared to plg_image_light, it trades speed for easier to install as it doesn't require any system dependencies to work.

I'm not aware of anyone else at this point who had develop a plugin.

> Conversely, if I write a useful plugin, it would be nice to advertise it to others who might be interested.

Fully agree, I think the easiest for now would be to advertise it on the website at the [plugin section](https://www.filestash.app/) with a link to your repo. In the long run I'm not sure how this should be done as [the plugin bit](https://golang.org/pkg/plugin/) of the golang standard library is far from perfect:
-  plugins only works on OSX and Linux. I initially thought it was just a matter of time but after having a chat with some golang guru on their IRC channel, it seems they have little interest in improving support there
- plugins needs to be recompile at every deployment to work correctly. As a consequence, plugins are only compatible to a specific commit the build was made with which is far form ideal

Because of those pain points, I'm thinking of some other approaches for plugins ([example](https://github.com/hashicorp/go-plugin)) but had little time to experiment there. Feel free to share ideas.

> The second one is more indepth documentation on writing plugins

At this point, from a design perspective, I'm not sure what's the best approach to build plugins:
- attempt to fix the plugin issues by contributing to the go standard library
- have some standalone packages that talk together either via RPC, JSON, ...
- maybe something different I have no idea about at this point?

The design bit of the plugin didn't move much forward since a few months as it would requires quite a lot of time to build, test, try and repeat.

Although, at this stage there's 2 type of plugins:
- backend plugin: which implement [this interface](https://github.com/mickael-kerjean/filestash/blob/master/server/common/types.go#L10-L20)
- hooks: which plug themselve somewhere along the request lifecycle. The image transcoding at this point is one of these but I had hope to build more for things like encryption or other custom things

Plugins needs to be placed in the correct folder and contains [this function](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_heavy/index.go#L12) which can then register itself as a backend or a hook (or both). The config object you receive can be used to declaratively CRUD the configuration that's accessible in the admin section with [a simple API](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_heavy/index.go#L13-L14)

**Comment by mickael-kerjean** [comment]
Should be much better now:
- [plugin documentation](https://www.filestash.app/docs/plugin)
- to publish a new plugin and advertise it to other: [PR to this section](https://www.filestash.app/docs/plugin#plugin-marketplace)
