### ISSUE TITLE
unable to acces through domain

### ISSUE THREAD

**Issue by jeroenpardon** [mickael-kerjean/filestash#144]
I would like to use this but unfortunately so far it has been a tad frustrating trying to set this up

I am getting the same error and behaviour as reported in https://github.com/mickael-kerjean/filestash/issues/127

`{"status":"error","message":"Not Allowed"}
`

However I am using the latest stable docker build.

The only way I can access both the admin and login pages is by either:

**Leaving the APPLICATION_URL empty** 
This makes /admin and /login accessible from within my local network and remotely through using a remote proxy. As a result though I cannot use Dropbox and Google as the redirect URI obviously is not usable

or 

**Setting APPLICATION_URL to the IP:PORT of my server using Portainer** (setting it as a variable in the docker-compose file doesn't work for some reason, even though the same values are used)
This at least passes a redirect to Dropbox and Google but as it uses a local IP this won't work

Whenever I set the APPLICATION_URL to my domain name I get the {"status":"error","message":"Not Allowed"} any time I try to access the /login page. I have tried with and without http(s), with and without /login, I am basically out of ideas on what to try.

Any pointers would be appreciated. Is there anything on the reverse proxy side I should look into for example?

**Comment by mickael-kerjean** [comment]
> Whenever I set the APPLICATION_URL to my domain name I get the {"status":"error","message":"Not Allowed"} 

The error you're seeing is a security mechanism that's get enabled once APPLICATION_URL is set. Basically the backend refuse to handle request coming from a different domain than the given APPLICATION_URL

>  Is there anything on the reverse proxy side I should look into for example?

That's a possibility but you need to identify the root cause first. Your logs (see `/admin/activity`) should give you more details about what went wrong with something along the line of: `2019/03/13 10:36:10 ERROR Invalid access from host: filestash.example.com:8334`
In this scenario you need to set `APPLICATION_URL=filestash.example.com:8334`

If you can't see your domain in the log, then it would be a problem coming from your reverse proxy which doesn't forward the host information properly. If your reverse proxy is a problem, you need to configure it properly, some example are given in the [documentation](https://www.filestash.app/docs/install-and-upgrade)

**Comment by jeroenpardon** [comment]
So before I might have used my local IP:PORT as APPLICATION_URL, so I binned everything and started over. This time setting the APPLICATION_URL to my domain and port.

However, still the same problem. In the logs the error you mentioned _is_ showing up however it is mentioning an issue with my local IP:

```
ERROR Invalid access from host: 192.168.1.20:8334
```

But I am absolutely sure I am not using my local IP but my domain...

I have looked into my reverse proxy configuration but can't really see anything wrong with it. I am using it to host about twenty other applications. I tried using a copy from the documentation, but no dice unfortunately. 

I am totally puzzled here

**Comment by mickael-kerjean** [comment]
> But I am absolutely sure I am not using my local IP but my domain...

In your scenario, Filestash doesn't see your domain => reverse proxy problem. You need to make sure your configuration is good enough, the documentation provide an example using nginx
```
location / {
       proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        ....
}
```

**Comment by jeroenpardon** [comment]
Ah, `proxy_set_header X-Forwarded-Host $server_name;` was the missing link here. Everything properly being forwarded now, excellent.

Thanks so much for the help, it's appreciated.
