### ISSUE TITLE
WebDAV Authentication Scheme

### ISSUE THREAD

**Issue by luehm** [mickael-kerjean/filestash#149]
Hello,
Very interested in your product, however I can't seem to get WebDAV working properly. I've tried both Basic and Digest authentication schemes on my Apache server with minimal dice. 

I've glanced through the repo and seems like Nuage is using Basic? Any tips/tricks on how the WebDAV should be set up? It's been working fine on my other apps so far. It's currently operating out of a web directory - is that an issue?
Thanks,
luehm

**Comment by mickael-kerjean** [comment]
Hello,

> I've glanced through the repo and seems like Nuage is using Basic?

Yes: see [here](https://github.com/mickael-kerjean/filestash/blob/master/server/model/backend/webdav.go#L216-L218). Digest authentication hasn't been implemented at this stage but pull request are welcome

> Any tips/tricks on how the WebDAV should be set up?

I made some test using the webdav server from Apache and Owncloud/Nextcloud (which is based on sabreDAV). To make it work with Apache, I've followed this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-configure-webdav-access-with-apache-on-ubuntu-14-04) but with Basic Authentication instead of Digest

> It's been working fine on my other apps so far. It's currently operating out of a web directory - is that an issue?

No. The only problem would have to an unprotected webdav server operating on the internet

**Comment by mickael-kerjean** [comment]
> Any tips/tricks on how the WebDAV should be set up?

I've already personally tried a few ways. The best solution depends on your situation:
1. manually create your user/password using a htpasswd
2. use LDAP as the database of user using [this](https://httpd.apache.org/docs/2.4/mod/mod_authnz_ldap.html)

The simple solution is akin of `htpasswd -c /etc/apache2/.htpasswd username` and update your `/etc/apache2/site-enabled/000-default.conf`: 
```
<VirtualHost *:80>
   DavLockDB /var/www/DavLock
   ....
   ....
   <Directory /var/www/webdav>
       DAV On
       AuthType Basic
       AuthName "Restricted Content"
       AuthUserFile /etc/apache2/.htpasswd
       Require valid-user
   </Directory>
</VirtualHost>
```

**Comment by luehm** [comment]
Excellent and thank you for looking into this. The issue turned out to be docker/iptables fighting with firewalld/qemu/kvm on the host. I've moved the docker container so there is no longer a war between firewalls. Everything is working as it should. I'll say though that having "Invalid password" be the default error message (even when it can't communicate with the destination server) is quite confusing.

I'll look into the WebDAV/ldap configuration you shared, that sounds appealing to me.

Thanks again for quick responses.
