### ISSUE TITLE
Question Mark in folder/filenames

### ISSUE THREAD

**Issue by alex-phillips** [mickael-kerjean/filestash#157]
The app is unable to open files / folders with question marks (?) in the names. This should be easily resolved by URL encoding the filenames when generating the links.

**Comment by alex-phillips** [comment]
Same issue for file/dir names with `%` in them.

**Comment by Jip-Hop** [comment]
Could this issue be reopened? I just created a file named `testwith?` on the [https://demo.filestash.app](https://demo.filestash.app) demo instance using the TMP backend. After adding some text to the file I end up with two files:

<img width="833" alt="Screenshot 2022-05-08 at 15 51 07" src="https://user-images.githubusercontent.com/2871973/167299542-83f078ec-aea6-4157-bb0d-83c80ff68f0d.png">

One with the ? and another one with the question mark encoded.

I also uploaded an MP3 file (two times the same file, just different name). The one with the question mark can't be played back due to: "Error decoding audiobuffer". The one without ? plays fine.

I'm having a similar problem with a my own installation using the local storage backend. But the error message is different. Trying to play the MP3 with ? in the name I get: "XHR error: Internal Server Error". The one without ? works fine.

On the local storage backend, creating a new file with a ? in the name works but I can't open/edit the file: `Oops!
Open /mnt/filestash/question%3F: no such file or directory`.
