### ISSUE TITLE
No prompt for admin password

### ISSUE THREAD

**Issue by Kesom** [mickael-kerjean/filestash#162]
Clean installation on a debian jessie host using docker.
No prompt to setup an admin password. It goes directly to /login. The software works as expected such as log into webdav and sharing files but I got no access to /admin.
I've deployed filestash behind a remote reverse proxy powered by Caddy with all the correct headers forwarded but I've tested direct access as well and no dice. I'm locked out of /admin.

**Comment by mickael-kerjean** [comment]
That's quite an odd behavior. To fix this, I'd need to understand what's happening, hence having a way to replicate this issue. 

Which browser are you using ? Which version? Does this happen on a different browser? Can you try to start the application and access it without Caddy?

**Comment by smnssn** [comment]
Same problem here, using Firefox. No reverse proxy, just running everything local so far.

**Comment by Kesom** [comment]
I've tried Firefox, Google & Edge. All updated. I'm using the machines/filestash image which is also updated. I've tried to connect directly to the server, without the reverse proxy in front. Nothing works. I get no prompt to enter any admin password.

**Comment by mickael-kerjean** [comment]
I just managed to get a repro on a clean server, investigating

**Comment by mickael-kerjean** [comment]
A dumb mistake from my end in [the build](https://github.com/mickael-kerjean/filestash/blob/master/.drone.yml#L75) that set the default admin password to "testing" to get smooth e2e test without being showed the welcome screen all the time.

@smnssn: "set a master password" the master password is a browser side feature that powered the remember me feature so that anyone with a physical access to your laptop can't find your credentials without the "master password".

**Comment by mickael-kerjean** [comment]
You should be good to go with the above commit that just got deployed to the docker hub. I'm closing but feel free to comment if anything is wrong and we'll reopen back
