### ISSUE TITLE
SFTP with private key fails

### ISSUE THREAD

**Issue by smnssn** [mickael-kerjean/filestash#164]
I have no luck with the private key for SFTP, as far as I understand not related to #89. This might be user fault since I'm new to this, but that's a good starting point for contributing to the documentation.

SFTP using atmoz/sftp docker container, key generated by:
ssh-keygen -t ed25519 -f ssh_host_ed25519_key < /dev/null

Verified to work using sftp from shell.

Text from the generated key file, between the BEGIN/END-sections, copy-pasted into Host key section of SFTP login. Key password supplied in Password section.

Logs from Filestash container returns:
ssh: handshake failed: ssh: no key found

**Comment by mickael-kerjean** [comment]
Look like there's a bug somewhere. Will fix when I got some time

**Comment by mickael-kerjean** [comment]
Made some test from my end and everything is working fine. Essentially you just need to paste your private key as your password and everything should be fine. Can you give a repro somewhow?

**Comment by smnssn** [comment]
version: '2'
My docker-compose.yml looks like this.

services:
  sftp_temp:
    image: atmoz/sftp
    volumes:
      - /opt/sftp/keys/ssh_host_ed25519_key.pub:/home/user/.ssh/keys/ssh_host_ed25519_key.pub:ro
    networks:
      - sftp_net
    ports:
      - "2223:22"
    command: user::33:33

  filestash_temp:
    image: machines/filestash:latest
    restart: always
    networks:
      - sftp_net
    ports:
      - "8335:8334"
    restart: unless-stopped

networks:
  sftp_net:
    external: true



Connecting using sftp in the terminal works fine:
sftp -P 2223 -i /home/user/.ssh/ssh_host_ed25519_key user@server_ip

But connecting via Filestash gives:
ssh: handshake failed: ssh: no key found

**Comment by mickael-kerjean** [comment]
Everything look good to me. Though I reread your initial message carefully and found a few things off that might be related.

> Text from the generated key file, between the BEGIN/END-sections

You need to copy and paste the entire key not just what between BEGIN and END as Filestash would have no way to tell the difference between a password and a key (see [here](https://github.com/mickael-kerjean/filestash/blob/master/server/model/backend/sftp.go#L57-L71)). Also that needs to be paste in the password section not the host key.

> copy-pasted into Host key 

The host key is NOT your private key, it is the thinghy to ensure you're not victim of a MITM attack that prompt your CLI upon first connection to a external server where it asks for yes/no. It matches what you have in ~/.ssh/known_host. But to really understand what's happening here, let it blank and once you got it right, then put the proper value

If this doesn't help, then you'll need to send me something to perform my own test so that I can replicate this as for now I can't replicate the problem you're experiencing

**Comment by smnssn** [comment]
Yes, seems like I've misunderstood where to put the key. I still get password error, but that would be another issue.

**Comment by mickael-kerjean** [comment]
I'm closing as I don't see any activity on this issue anymore. Feel free to comment back and we'll reopen
