### ISSUE TITLE
MKV are loading... Loading...

### ISSUE THREAD

**Issue by AaronActu** [mickael-kerjean/filestash#166]
Hi,

When I try to access .mkv files (or even by sharing them) I have the loading bar during a while and if it succeed - after more than 15mins of loading - to load the page, after downloading file is not always complete.

You can check it here : https://filemanager.cafecloud.fr/s/CH6J2IZ

Thanks !

**Comment by mickael-kerjean** [comment]
Hello,

I see yes this should definitely be fix. Feel free to send a pull request

**Comment by AaronActu** [comment]
Hi Mickael,

Thanks for your quick answer.

I'd like to make a PR but I don't know Go at all :(

Did you mean you fixed it? Or it should be? ^_^'

I'm running FileStash with the official Docker ct, should I pull it to get the latest version, then run it again?

Thanks for help!

**Comment by mickael-kerjean** [comment]
> It's working pretty fine, however with the auto-login link... it doesn't: 

The auto connect is a undocumented features that was created for the need of a customer.
 
> Did you mean you fixed it? Or it should be? ^_^'

Filestash is an open source project. We welcome you to contribute with code for the features you need and share it with the community. Otherwise, you can enroll with our enterprise plan if you required our assistance when it comes to support and maintenance,
