### ISSUE TITLE
[bug]  Safari IndexedDB

### ISSUE THREAD

**Issue by Keyboardsmasher12** [mickael-kerjean/filestash#202]
When using a iframe to display the file manager while using safari i get an issue in console saying "IDBFactory.open() called in an invalid security context" this causes filestash not to be displayed. Is there any way im able to fix this I don't know any go so kinda stuck.

**Comment by mickael-kerjean** [comment]
Filestash is using indexedDB as a caching layer to make navigation feeling faster. If safari doesn't support it via an iframe, the only viable solution that don't degrade the user experience too much would be to create additional caching implementations, eg one that rely on RAM to store its data.

Considering I have no need for using Filestash via an iframe and the time it would require to make it happen, I won't personally attempt that kind of development on my free time, feel free to send a pull request

**Comment by BobCashStory** [comment]
@Keyboardsmasher12 we pushed a fix for that : https://github.com/mickael-kerjean/filestash/pull/207

**Comment by mickael-kerjean** [comment]
@BobCashStory such a fix isn't acceptable to me as it gives no consideration to why indexedDB was used in the first place and degrades the user experience to a level I'm not comfortable with. This try catch path is in fact the reason I wrote that **the only viable solution is to create additional caching implementation**

**Comment by BobCashStory** [comment]
@mickael-kerjean you have to understand it not usable at all for user in iframe right now the app appear simply broken . This is a quick fix to unbroken it .
it doesn't change the experience for 99% of users and let the 1% who where not able to use it to have a "degraded" experience.
Do you really prefer to let then with a broken app, since it could work without cache for this case ?

**Comment by BobCashStory** [comment]
@Keyboardsmasher12 also if you use firefox or safari in private mode your cache system don't work but the app work since indexedDb can be call and return error, so this fix make it work same as firefox or safari private tab, not less not more, could you allow that ?
https://bugzilla.mozilla.org/show_bug.cgi?id=781982
https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/indexeddb-best-practices

**Comment by mickael-kerjean** [comment]
> Do you really prefer to let then with a broken app, since it could work without cache for this case ?

Yes. I prefer to not support something than doing it in a poor way that degrade the user experience. At this stage, using Filestash from an iframe isn't supported and I value doing things right, not "unbroken it" especially when it means the user experience will become suboptimal as a result.

> it doesn't change the experience for 99% of users and let the 1% who where not able to use it to have a "degraded" experience.

People who want to use iframe might be a small number when we enable this feature, this is no reason do give them a "degraded" experience because it was quicker fix


Also I found an interesting use case on which I will be using iframe in the future so I will at some point look at this if nobody did push a clean solution before

**Comment by riderx** [comment]
@mickael-kerjean it doesn't make sense since this is happening in Firefox and Safari in private browsing, and you let user use the "degraded" experience.

**Comment by BobCashStory** [comment]
@Keyboardsmasher12 if you need a fix for your usage you can use our public image https://hub.docker.com/r/cashstory/filestash
it came from : https://github.com/BobCashStory/filestash?organization=BobCashStory&organization=BobCashStory
main change are a more standard docker approach and this fix .

**Comment by mickael-kerjean** [comment]
This is going nowhere, I've already made my point as I'm open to a pull request but it needs to be done properly. Also your "more standard" docker is an untested heresy, we already talked about it.

Also I'm restricting this issue as it is getting more of a time sink compared to creating a PR to solve it properly

**Comment by mickael-kerjean** [comment]
This issue has been fix in 44310fbab0ccc8480fbd5720efee8bff0bc8868f
