### ISSUE TITLE
[bug] Proper docker support and docs

### ISSUE THREAD

**Issue by subdavis** [mickael-kerjean/filestash#222]
Hello!  First of all, thanks for building this! It fulfills a lot of my needs and is a rather uniquely positioned product in that it appears to have no reasonable competitors.  I have a lot of data hosted in a Minio instance, and I needed a more user-friendly access layer with indexing, search, and especially thumbnail generation.  This seems to do those things well.

#113 gets into these issues a little, but I want to be a bit more specific.

## Current docker image is insufficient for production

**Documentation**

For the current docker image, documentation is, as far as I can tell, missing entirely.  This is what really good docker documentation looks like: https://github.com/linuxserver/docker-syncthing#docker
 
After looking at the docker-compose file and the docker image, I still didn't know what to do.

`docker run --rm -v /local/path:/app/data machines/filestash` results in a message about missing access logs.  There should not be volumes in the dockerfile if mounting them breaks everything.

I was able to get things running with:

```
docker run -d --name filestash machines/filestash
docker cp filestash /app/data:/local/path
docker stop ...
docker run -v /local/path:/app/data machines/filestash
```
But this is entirely a hack, and it will break when the directory structure changes with [no mention in the changelog](https://github.com/mickael-kerjean/filestash/releases)

**What should happen**

I've looked through the code, and in some places you `os.MkdirAll(cachePath, os.ModePerm)`.  In others you don't.  That's fine, but if you aren't going to `MkdirAll`, you need to document it so that the user can provide a bind-mount directly to the folder.

For example: https://github.com/mickael-kerjean/filestash/blob/762977190dccb761b4a2894a72f1343b6ae6c493/server/common/log.go#L16

## Docker compose is not for production

It's fine to have this, but a docker-compose file doesn't count as documentation. An example of a `docker run` like in the syncthing example above is a bare-minimum.

Also, what is `APPLICATION_URL` for?  Are there other environment variables I can use? I shouldn't have to search the code for instances of `os.Getenv` to find out what environment variables and expected values are.  Document these. 

## Upgrades

This is actually my biggest concern about relying on filestash.  What happens when there's a new version?  Does the server run database migrations?  Do I have to totally delete my caches, indexes, etc?

## Suggested fixes:

1. Add documentation of `docker run` and all its possible env, options, volumes.
2. Add `os.MkdirAll` everywhere, so that `-v /local/path:/app/data` can be used.  I restart my containers nightly, and I don't want to lose my thumbnails and everything else every day.
* Add documentation for how upgrades will (or won't) work.  Provide migrations for what you can, and document what you can't.  

Thanks again for providing this project.  If you'd like help with 1 or 2 above, I'm happy to try a pull request.  If financial support for 3 is needed, maybe add it to the opencollective budget and I can pitch in a bit?

**Comment by mickael-kerjean** [comment]
> documentation is, as far as I can tell, missing entirely

There's already a big chunk of documentation on [the website](https://www.filestash.app/docs/install-and-upgrade/). It could sure see a lot of improvements but I have personally 0 fun in writing documentation which is the reason the documentation pages all got a button with "Want to contribute to this page? Edit this page!". Receiving help to contribute to the documentation is a sure way to get it better. 

> After looking at the docker-compose file and the docker image, I still didn't know what to do.

It is shown [there](https://www.filestash.app/docs/install-and-upgrade/#installation), the recommended installation process is just 3 commands long. Also I've made a poll (#215 ) to see if there's interest in creating a video tutorial about the installation but it hasn't really took off much, way less than 1% of the install page visitors did bother to bring their vote and respond positively

> results in a message about missing access logs. 

Using docker directly isn't the recommended way to install Filestash. By using `-v /local/path:/app/data` you are flushing the entire content in `/app/data` which contains a lot of config, public files serve by the server, cache, ...

> I was able to get things running with ...

If you really don't want to use docker-compose, such an approach should be fine. As a tip, you shouldn't persist `/app/data/` but `/app/data/state/`. This will make upgrade possible down the road. This is effectively an issue with the current Dockerfile that is waiting for a pull request from someone interested in fixing it

>  That's fine, but if you aren't going to MkdirAll, you need to document it

I don't understand what you are saying here.

> Docker compose is not for production

It depends on the scale you are operating. For simple requirements, docker-compose is very fine in production. If you need more, I can provide support service to get all the high availability, 24/7 support and other tips to make the most out of it depending on what you are using it for

> An example of a docker run like in the syncthing example above is a bare-minimum.

The example above would represent a massive amount of work and as mentioned above I have no fun at all writing documentation. Pull request on the documentation site is actively encouraged.

> Also, what is APPLICATION_URL for?

This has been answered on the [community support portal](https://support.filestash.app/?q=APPLICATION_URL) a few days ago. The `APPLICATION_URL` env variable is used in many places:
1. security: Filestash default to verify that the host header which is generally sent by browsers do match that variable.
2. used by the HTTPS plugin to automatically create SSL certificate either selfsign one or coming from Let's Encrypt
3. used in the authentication process of backend plugins like Google Drive or Dropbox to generate the redirection URL from which those plugins can then interact with your Google Drive or Dropbox account.
4. integrate with the openoffice container to support file viewing/editing of word/excel/ppt documents

> Are there other environment variables I can use? 

Yes but to find them today, you have to search through the code, this hasn't been fully documented

> I shouldn't have to search the code for instances of os.Getenv to find out what environment variables and expected values are. Document these.

As mentioned before, I don't enjoy writing documentation on my free time. Open source work doesn't mean free labor. When someone is interested, I'm happy to consult them to give more details about the sheer amount of customisation and setup possible to match a specific use case.

> This is actually my biggest concern about relying on filestash. What happens when there's a new version? Does the server run database migrations? Do I have to totally delete my caches, indexes, etc?

When it comes to upgrades, I have an extremely limited visibility over how people are doing it as less than 1% of total users decide to enable telemetry. For those that did, I didn't see any problems and on the overall project, I haven't heard about any complain of a breakage. Though I agree those concerns are perfectly legit, if you need to rely on Filestash for anything serious, I'd advise to buy proper support.

> Add documentation of docker run and all its possible env, options, volumes.

To date, using docker alone isn't the recommended way of doing things, docker-compose is. As much as it did made my life much easier for distributing Filestash, I'm looking into getting rid of docker in the long run, moving torward a simple binary. Before this happen, there's still some issues that needs to be solve:

1. design a plugin API to assert some tools are installed in the machine + reporting of such dependencies in the admin console

2. remove the hard dependencies on things like pdflatex and emacs for org mode related features

3. ~~Statically compile the C libraries we're using~~ this has been done, a few weeks ago, it tooks a whole lot of time to get right as I'm not a GCC gourou and having dependencies on the glib is a ~~massive pain in the ass~~ struggle.

> Add os.MkdirAll everywhere, so that -v /local/path:/app/data can be used

It might not be as obvious, such as solution can potentially brings its own set of problem when it comes to performance (which I haven't benchmark) or even solve any problem at all as you still need to ensure both access right and ownership of your volume has been set correctly considering the current container doesn't run as root but as its own user. I'm open to the discussion but that would need to be in a new issue

> and I don't want to lose my thumbnails and everything else every day.

I wouldn't worry about this as Filestash doesn't store thumbnails anywhere, those are generated on demand and cached by the browser with a cache policy that is proportional to the time it takes to generate the thumbnail. This might sound wastfull but the C library I use (libvips) is extremely efficient at it and has shown to be an order of magnitude faster than other tools like imagemagick

> Add documentation for how upgrades will (or won't) work. Provide migrations for what you can, and document what you can't.

This is [here](https://www.filestash.app/docs/install-and-upgrade/#upgrade). It only covers docker-compose. Also I already made a point about migration a bit earlier that's valid here as well. Ultimately, the way I see it, creating more documentation is a balancing act between heading toward the future vs consolidating what's available now. I encourage anyone to help out with the documentation so that I can focus my limited time into building toward that my initial vision. Also, after having spend more than 2 years on this project, I have develop a tunnel vision making it impossible for myself to look at this project with a fresh new eyes which I believe is needed to make a great documentation.

**Comment by mickael-kerjean** [comment]
To summarise my comment above and have something actionable, I suggest the documentation is to be written by the community. This is mostly coming as having work on this project for more than 2 years, I have developed tunnel vision making it impossible for myself to look at the project with a fresh set of eyes which I think is required to make a great documentation. I'd be happy to answer any question from anyone willing to work on this

**Comment by ovizii** [comment]
hi there,

as I am currently also getting started with filestash and docker-compose let me add a few questions. 

Regarding: APPLICATION_URL you said:

> - security: Filestash default to verify that the host header which is generally sent by browsers do match that variable.
> - used by the HTTPS plugin to automatically create SSL certificate either selfsign one or coming from Let's Encrypt
> - used in the authentication process of backend plugins like Google Drive or Dropbox to generate the redirection URL from which those plugins can then interact with your Google Drive or Dropbox account.
> - integrate with the openoffice container to support file viewing/editing of word/excel/ppt documents

I plan on using filestash behind a reverse proxy which handles the certificate on its own so would I set this ENV variable with http or https?

Also, do you have any more documentation or links or explanation on how the open office container interacts with filestash and the other way around? When I found your docker-compose.yml example I saw that there is apparently some interaction between these two containers. 

what does one use for: ONLYOFFICE_URL=http://onlyoffice ? 
HTTP or HTTPS - does this URL need to be publicly accessible or does it only need to be accessible from the filestash container? COuld this be ONLYOFFICE_URL=http://onlyoffice-container-hostname ?

**Comment by mickael-kerjean** [comment]
> I plan on using filestash behind a reverse proxy which handles the certificate on its own so would I set this ENV variable with http or https?

APPLICATION_URL is your domain name. For the demo (https://demo.filestash.app/) it is set as `demo.filestash.app`

> what does one use for: ONLYOFFICE_URL=http://onlyoffice ?

whatever is need to reach the only office server from a Filestash point of view. For example, if you use the [docker-compose](https://github.com/mickael-kerjean/filestash/blob/master/docker/docker-compose.yml) it is rightly preconfigured as "http://onlyoffice"

>  is that comment up to date?

yep

> Question regarding persisting data I found 2 threads with differing structures, could you maybe let me know which one is the latest one?

#183 is the correct one

> Also, do you have any more documentation or links or explanation on how the open office container interacts with filestash and the other way around?

This hasn't been documented as of today (hence this issue :bowtie:). Basically, onlyoffice is loaded as an iframe pointing to a Filestash API that's reverse proxifying the traffic to onlyoffice:
```
+-----------+                   +----------------+                   +------------------+
|           +-----------------> |                +------------------>+                  |
|    User   |                   |   Filestash    |                   |   Only Office    |
|           +<------------------+                +<------------------+                  |
+-----------+                   +----------------+                   +------------------+

```

**Comment by suckerfish** [comment]
I suppose I'm having issues similar to folks in this thread but maybe not quite as experienced as others. 

I would also like configs and any other directories that could use a lot of data to persist on my host side as a volume mapping. 

I did notice that whenever I try to play a video, the cache process builds somewhat large files. I don't want these in the docker container, but on a host side share. However my attempts to map volumes have failed to make this work. I believe(?) mapping /app/data/state is okay, but /app/data/cache seems like a no-go and I don't know why. Not sure if it is permissions or something else. 

I want as little as possible within the container, especially if something like cache is expected to take up potentially gigs or more. Thanks!
