### ISSUE TITLE
ARM and ARM64 support

### ISSUE THREAD

**Issue by ViRb3** [mickael-kerjean/filestash#233]
Hello,

I noticed there was some ongoing effort to support ARM in #142, so I wanted to create a new issue and offer a solution. You may not be aware that Drone CI support both ARM and ARM64 builds on their free tier, making our job a piece of cake 😄 

I created a [fork](https://github.com/ViRb3/filestash) of your repo and modified the `.drone.yml` to build for ARM. You can find the diff [here](https://github.com/ViRb3/filestash/commit/0c80b316ae68e8fa9354f1064b2c1e7465650f47). I have left you comments on each change and why it was necessary. Obviously I had to remove all the proprietary tests and change the release mechanism. I haven't submitted an actual PR because I can't test if it will work properly with your setup.

I tested my fork's [release](https://github.com/ViRb3/filestash/releases/tag/v0.41) on my Raspberry Pi 4 running Ubuntu ARM64, and by using an ARM base image (`FROM arm32v7/debian:stable-slim`), everything works perfectly.

I wanted to build for ARM64 directly, but I realized that your [prebuilts](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_light/install.sh) don't include ARM64. If you update them, simply changing the `.drone.yml` target to `arm64` will make everything work.

In order to have multiple pipelines you can follow the [docs](https://docs.drone.io/pipeline/configuration/) and have 3 copies of your drone configuration in `.drone.yml`, each with a different architecture. If you feel extra fancy you can script the configuration with [Starlark](https://docs.drone.io/pipeline/scripting/starlark/) to avoid the duplicate code.

If you have any questions feel free to ask away!

**Comment by mickael-kerjean** [comment]
Thank you for your help. 

> If you update them, simply changing the .drone.yml target to arm64 will make everything work.

The reason this hasn't been done yet is I don't have some hardware that I can dedicate to the build, this is not about drone support

**Comment by ViRb3** [comment]
Drone Cloud will provide you with the hardware for ARM/ARM64, you just need to set up a `.drone.yml` for it to build.

**Comment by amilino** [comment]
Does it mean that ARM/ARM64 (armhf) builds might be included in new releases in the future? That would be awesome!

**Comment by mickael-kerjean** [comment]
> Drone Cloud will provide you with the hardware for ARM/ARM64

I wasn't aware of Drone cloud before. This looks pretty good and although I really like Drone, I have quite a lot of things running on my current instance. Because of that background, I have no plan to migrate to Drone Cloud.

> Maybe have a separate repo to build the prebuilts? 

That's an option. To be more precise, I see 2 options:
1. a backer need that and I'd use the open collective contribution to pay for an ARM server to be used for the build - eg: [cheap scaleway instance](https://www.scaleway.com/en/virtual-instances/arm-instances/)
2. someone making a fork and get that fork to be build by Drone Cloud. There's literally a space on the documentation for [Alternative Installation methods](https://www.filestash.app/docs/install-and-upgrade/#alternative-installation-methods) and I invite anyone to contribute to it

**Comment by amilino** [comment]
Any news?

**Comment by ViRb3** [comment]
I don't use this project anymore, but it should be trivial to use Drone Cloud to build for ARM/ARM64. I don't see @mickael-kerjean's point for needing an extra instance to support this build, as Drone Cloud will cover 100% of it and push binaries to his existing infrastructure.

**Comment by amilino** [comment]
Thank you for your input. Are you using some other similar project?

**Comment by andresmazzo** [comment]
Would be great ARM support to expand project to SBC! :muscle: 
Fundamentally for NAS, that could have an FTP Server and user wants to empower it with Filestash.

**Comment by amilino** [comment]
I am also walking away from this projects, so have no time to spend on forking and doing Dron setup.

**Comment by gprst** [comment]
Hey, I have an ARM64 SBC and I digged a little bit into the problemathetic plugin, namely `plg_image_light`, and thanks to your awesome `create_libresize.sh` and `create_libtranscode.sh` scripts, I've been able to tinker a little bit and compile the dependencies for the ARM64 architecture.

Then I forked @ViRb3'f fork (great job 👍 and indeed, Drone CI is soooo easy to setup, what a great tool) for the `.drone.yml` file. My changes can be seen [here](https://github.com/gprst/filestash/commit/1708a4ce68b35fbe15b8ddaab7e32685f8de5997).

Now, imho, the thing is, here are the possibilities for the `.drone.yml` file, to support multiple architecture :
- find a way to factor architecture-specific pipelines (jobs should differ for `build_frontend` and `build_backend`, but the others should be the same), with each one targetting a specific architecture with the `arch` flag (e.g. `arch: arm64`)
- or keep it as it is, and include both `python2` and `build-base` packages (@ViRb3 👏) for all architectures during the `build_backend` part

Also, as of my commit, I didn't use a specific name for `libresize.a` and `libtranscode.a`, which should be `libresize_linux_arm64.a` and `libtranscode_linux_arm64.a`, do you think I could dynamically specify a name for the compiled archive, depending on the architecture ? Also, I guess you might want to pre-compile these files and get them with curl, you tell me.

I would be glad to submit a PR, tell me what changes you would like to see on your repo.

**Comment by gprst** [comment]
(Also this is my first time contributing code on GitHub, I didn't know that my commits referring to this issue would be shown, my bad)

**Comment by mickael-kerjean** [comment]
> would be glad to submit a PR, tell me what changes you would like to see on your repo.

The project already work with ARM, the heavy work has already been done (as you've seen with `create_libtranscode.sh` and `create_libresize.sh`). The only missing part is a prebuild image that can be pulled from the docker hub and the only reason this is not hapening at this stage is because nobody did donate the hardware to make such build hapenning.

If you want to work on a PR for prebuild images using ARM without donating the hardware to get an official build, there's an [alternative installation section on the documentation](https://www.filestash.app/docs/install-and-upgrade/#alternative-installation-methods)

> Also, I guess you might want to pre-compile these files and get them with curl, you tell me.

I'm not sure to understand, the current situation is shown [here](https://github.com/mickael-kerjean/filestash/blob/master/.drone.yml#L39) where the static libraries are getting pulled [via curl already](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_light/install.sh). Creating those static library at build time would take an unecessary large amount of time and wasting a large amount of CPU.

**Comment by gprst** [comment]
Okay ! I'm currently trying really hard to build a Docker image on my SBC (I am really not familiar with this, but it is fun), and using the `docker build` command keeps me getting the same error :
`gpg: decrypt_message failed: Unknown system error`
Even though I cheated a little bit and specifically asked for the `filestash_Linux-x86_64.tar.gpg` file on [this line](https://github.com/mickael-kerjean/filestash/blob/master/docker/Dockerfile#L13) of the Dockerfile, since there doesn't seem to be any `Linux-armv7l` variant — nor `Linux-aarch64`, obviously. Do you have an idea of what I am doing wrong ?

> The project already work with ARM

I guess so, but it unfortunately doesn't on ARM64 (or at least, not on my board, apparently because of plg_image_light).

> the static libraries are getting pulled via curl already

Yes they are, but there are none for ARM64 devices ; what I was suggesting was that you used Drone CI with the `arch: arm64` property and uncommented [these lines](https://github.com/gprst/filestash/blob/feature/arm64/server/plugin/plg_image_light/deps/create_libresize.sh#L89-L95) of my modified `create_libresize.sh` and `create_libtranscode.sh` files to send the archive files to your server, so that they could be fetched with curl by ARM64 devices. Am I getting it wrong ?

I could still make a bash script for installing everything on an ARM64 device following [your tutorial](https://github.com/mickael-kerjean/filestash/issues/142#issuecomment-576127077) tweaked so that it works on such devices, but it would be less fun that building a Docker image ! (I actually think I wouldn't find enough motivation for such a script)

**Comment by gprst** [comment]
I think I managed to successfully build and run a Docker image of filestash for arm64 devices. I am going to work on a PR for the alternative installation section of the documentation during the next days :)

**Comment by gprst** [comment]
Okay :
- [here is my fork](https://github.com/gprst/filestash/tree/v0.42-arm64)
- [here is my last commit](https://github.com/gprst/filestash/commit/b967c9026cbf3e9065af7dad805851cd8963c8ed)
- [here is my Docker image](https://hub.docker.com/r/gprst/filestash)
- [here is the compiled software](https://github.com/gprst/filestash/releases/download/v0.42-arm64/filestash_Linux-aarch64.tar) for those who want to use filestash on arm64 devices without relying on Docker

Now, about what will happen next :
- What do you expect from me for the alternative installation section on the documentation ? I saw that the only community documented guide reedirects to an unmerged pull request.
- Do you plan to build libresize and libtranscode dependencies for arm64 devices ? You could use my changes on [create_libresize.sh](https://github.com/gprst/filestash/commit/b967c9026cbf3e9065af7dad805851cd8963c8ed#diff-ade3821b3aacc05b77437c2fa9995c1f) and [create_libtranscode.sh](https://github.com/gprst/filestash/commit/b967c9026cbf3e9065af7dad805851cd8963c8ed#diff-90314ae7790ec80a7f0a43273d81fd81) to build these dependencies via Drone CI and send them to your server so that they could be accessible via curl in a cleaner way than [this](https://github.com/gprst/filestash/commit/b967c9026cbf3e9065af7dad805851cd8963c8ed#diff-567bb55bb86606c02ee4608bbd42c9f1).

Then, I guess that as long as you cannot build an official Docker image for arm64 devices, I can (and am willing to) maintain for some time an unofficial Docker image for arm64 devices, based on the latest changes on your master branch.

Your work is amazing, and I really hope what I did could be of some help.

**Comment by amilino** [comment]
What about armhf build?

**Comment by mickael-kerjean** [comment]
> What do you expect from me for the alternative installation section on the documentation 

I don't expect anything from anyone but welcome contribution on the documentation. A link to your [github repo](https://github.com/gprst/filestash) with as you mentioned an updated README to say this relates to an arm64 build would be awesome

> I saw that the only community documented guide redirects to an unmerged pull request.

It's unmerged, as I don't want to see too many installation guide on the website, the reasoning is guides are a living thing and needs to be maintain to not become obsolete when whatever new version of debian, ubuntu or your favorite linux distribution comes in or new version of whatever dependencies becomes available on your favorite distribution. 
I can only afford as much time to do that work for docker, not the hundreds of other possible choices which would provide little benefits and stop the project from moving forward.

> Do you plan to build libresize and libtranscode dependencies for arm64 devices ?

Yes but I lack the hardware to work this out at this stage. cross compilation might be possible but I'm far from an expert in this area.

> You could use my changes on create_libresize.sh and create_libtranscode.sh to build these dependencies via Drone CI and send them to your server so that they could be accessible via curl in a cleaner way than this.

Sure, that's pretty good, thanks!

> But then, I guess I should modify the README.md file of my fork (that I could also rename in something like "filestash-arm64") to specify the responsibility of this fork.

Sounds great to me.

**Comment by amilino** [comment]
> What about armhf build?

Any answer for armkhf build for RPi?

One hint, if you want to put URL as a link to release in a more generic way here it is:
https://github.com/gprst/filestash/releases/latest/download/filestash_Linux-aarch64.tar

**Comment by mickael-kerjean** [comment]
@amilino Nothing from my end. The situation hasn't change from my end with [this](https://github.com/mickael-kerjean/filestash/issues/223#issuecomment-581667028) but also [this](https://github.com/mickael-kerjean/filestash/issues/142#issuecomment-471253446), [this](https://github.com/mickael-kerjean/filestash/issues/236#issuecomment-593901286) and accross a lot of post on the [support channel](https://support.filestash.app/?q=raspberry+pi). Ultimately I'm all for a raspberry pi build accross all possible architecture but not on my own dime as I don't need / use it directly.

**Comment by amilino** [comment]
That was a question for @gprst.

**Comment by gprst** [comment]
Hi, I didn't answer because I don't usually answer people that "walk away" from a project they haven't even "walked in" in the first place (no fork, no PR, no commit, nothing). What you are looking for is already available, I suggest you look for it, and if it doesn't suit your need, I guess you could still fork the project and code your way to what you deeply want, instead of being unpleasant and spamming issues with unrelevant comments.

If you don't want to contribute nor fork the project, I guess you can just wait. If someone ever makes what you want, I guess they'd just tell about it. Constantly asking for it won't by any mean accelerate the process.

**Comment by amilino** [comment]
I contributed by testing and preparing live test cases, but with lack of response gave up. Take care guys.

**Comment by orangethakkali** [comment]
I have 2 Pi4B available for testing if required.

**Comment by nycki93** [comment]
not stale
