### ISSUE TITLE
[Feature Request] Support JWT for OnlyOffice

### ISSUE THREAD

**Issue by ServiusHack** [mickael-kerjean/filestash#240]
The document server of OnlyOffice can be configured to require a JSON Web Token (see [their documentation](https://api.onlyoffice.com/editors/signature/)). It would be great if filestash supports integration with an OnlyOffice installation where a JWT is required.

**Comment by ServiusHack** [comment]
Following your Contributing Guide I've created this issue before sending a pull request. I've implemented this already though.

**Comment by mickael-kerjean** [comment]
Do you mind giving some context on the use case where you believe such a feature is beneficial? To date, I don't understand the problem such a feature would solve or even why such feature is in only office in the first place.

If you are trying to solve the "blocking unauthorized traffic to only office" problem, Filestash solves that by design as it is literally reverse proxyfying the traffic into onlyoffice so that you don't even have to expose your only office instance to the internet to start with

**Comment by ServiusHack** [comment]
I also have a hard time understanding what exactly the token is for. Other than rephrasing what is written on https://api.onlyoffice.com/editors/security I can't help much here.

My use case is an already running document server of OnlyOffice, which is configured to require a JWT. I'd like to reuse that instance with filestash. Running a dedicated instance just for filestash seems unnecessary to me.
