### ISSUE TITLE
[bug] Folder icons not displaying on fresh container

### ISSUE THREAD

**Issue by Cruv** [mickael-kerjean/filestash#244]
- description of the bug
Its seems that /assets/icons/folder.svg isnt loading or downloading on the first run of the app

- step by step instructions to reproduce the bug
For me it was a fresh install through my Portainer instance on Ubuntu 18

- observed behavior
Icons do not load. They show instead the default broken image icon.

- expected behavior
The folder.svg file I have seen in the screenshots should be showing when browsing folder objects.

**Comment by pbuyle** [comment]
I've a similar issue. The icon used to work but now they don't. The issue is cross browser/devices. I tried Firefox 74 on MacOS incl. in a anonymous window, Chrome on MacOS, Firefox on Android and DuckDuck Go Browser on Android.

The weird parts are
- The asset are there and direct access with their url (eg. https://my-domain/assets/icons/file.svg) works, they download just fine when using curl or the browser
- Changing the domain used to serve fiilestash solve the issue.

I use Filestash v0.4rc in the official Docker container behind Traefik 2 (AFAIK, it doesn't do any kind of caching).

**Comment by Cruv** [comment]
Any word on this?

**Comment by mickael-kerjean** [comment]
**Reason of the error:** If you see errors coming in the developer console with something about "application/octet-stream" and the links of the assets are indeed working when you access it directly, This is an issue where Filestash can't find its own configuration and specifically the mime.json which dictate the mime type the server need to return for a range of files.

**Root cause**: This is a known error that typically occur after creating a empty volume in the docker-compose which erase the Filestash config folder that contain among other thing this mime.json

**The fix**: either:
- remove the volume you are using
- keep the volume but recreate the folder the volume this is replacing and give it the proper access rights. The content of the config folder by default is given [here](https://github.com/mickael-kerjean/filestash/tree/master/config) and that content should be read/writable by the user with id 1000.

**Comment by acivitillo** [comment]
I think this might be a duplicate https://github.com/mickael-kerjean/filestash/issues/247

@mickael-kerjean is this something that maybe should go in the documentation? I might be wrong here, but it seems those issues are mostly solvable if they use a subdomain instead of a root domain for serving filestash.

**Comment by mickael-kerjean** [comment]
> @mickael-kerjean is this something that maybe should go in the documentation? 

I've worked around this in a different way with [this change](https://github.com/mickael-kerjean/filestash/commit/bdf8d9a93164d3ce2baa6e7d077d55cc91fc0ab3). The idea was to push the config files that's causing this issue onto the code itself so this specific config lives in the binary and isn't causing any problem when a volume is created and wiping the entire config folder.
