### ISSUE TITLE
[Feature Request]  Build instructions

### ISSUE THREAD

**Issue by constptr** [mickael-kerjean/filestash#251]
IMO, Since Filestash is written in Golang, it must be compilable into single static binary. 

Can you please provide build instructions atleast in README.md ?

**Comment by mickael-kerjean** [comment]
The link you're making with Golang => static binary isn't right. It's an objective since day 1 but it ain't simple:
- Filestash leverage some C library for the bit that requires a lot of CPU and where Golang wouldn't perform well (image resizing and transcoding for RAW images). If you can help to statically compile libvips on linux, this would be a big step in the right direction. [this](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_light/deps) is where I stopped, still a WIP at this point
- Filestash use third party tool. I still need to put my head around how to create an API to gracefully degrade the feature they support in a way that make sense for the user. For example: emacs is used for org-mode export, ffmpeg is used for video transcoding. If you can pull request something that work and gracefully degrade when dependency aren't there, that would be a step in the right direction
