### ISSUE TITLE
[Feature Request] Refresh button

### ISSUE THREAD

**Issue by pagdot** [mickael-kerjean/filestash#254]
Adding an refresh button on the UI to refresh the folder structure.
It seems like without a relogin there is no way to see external added files.

**Comment by mickael-kerjean** [comment]
Two things here, the problem and the solution. The problem is definitely worth solving but the solution you are giving would add clutter to the UI. A solution without clutter would be too have a mechanism to refetch the content of the current folder every x seconds. 

At the moment, I don't really have time to work on that kind of feature but this would make a great PR if you are keen to work something out.
