### ISSUE TITLE
[Feature Request] Using an HTML input element for login page password field

### ISSUE THREAD

**Issue by marier-nico** [mickael-kerjean/filestash#298]
Hey, thanks for creating Filestash!

I just started using it, and I already love it. This issue is a bit of a nitpick, but using an input element for the password field of the login page would be helpful for password managers. Personally, I use Bitwarden, and it doesn't support auto-filling into a textarea, so it's having trouble auto filling my credentials.

Thanks again! :smile:

**Comment by mickael-kerjean** [comment]
Thank you for the report. The password field on the SFTP and GIT backend appear as textarea to allow for multi-line password to support not only for regular password but also private key which contains multiple lines from one single input. That's the core reason of the hack and as I'm not using a password manager, I didn't imagine this could pose problem. 

As a bitwarden user, do you know how to enable the auto filling functionality without losing the multi line functionality for private key?

**Comment by marier-nico** [comment]
Ahhhh yeah, that makes a lot of sense now! Admittedly, I didn't really think of that use-case initially, but it makes perfect sense. However, I think that's not possible to do with bitwarden.

I know it's possible to fill custom fields with the form input element ID or the label name (if a label is used), or the placeholder text, but in the case of the password field for the SFTP backend, there doesn't appear to be either of those options, so I wasn't really able to work around the problem. I think one option would be to maybe add a checkbox to toggle between a regular password input and a textarea for a private key. Another option (I think, I'm not sure if this would work) might be to add an ID to the textarea, or some placeholder text for the field, or a label surrounding it.

Here's the documentation for Bitwarden's custom fields, maybe it's going to give you an idea for something : https://bitwarden.com/help/article/custom-fields/

**Comment by thielepaul** [comment]
I think that should have high priority as GBoard under Android 10 wants to autocomplete the password because it thinks this is a cleartext field.

![Screenshot_20200924-182209_Chrome](https://user-images.githubusercontent.com/2041078/94172693-1b4e8600-fe93-11ea-9065-a3f743a87c88.png)

**Comment by thielepaul** [comment]
I also read through the related issues:
https://github.com/mickael-kerjean/filestash/issues/58
https://github.com/mickael-kerjean/filestash/issues/217

Still, I do not understand why the password field should also be used for private keys.
They are both quite different in their nature, so why not just have two fields? Especially as it is possible that both are simultaneously required for a ssh login

**Comment by mickael-kerjean** [comment]
> Still, I do not understand why the password field should also be used for private keys

That's a design choice that was made to make things easier by non technical people who have no idea what's the heck is the private key so I could tell them: that's a secure version of your password, just paste it in the password section.

> They are both quite different in their nature, so why not just have two fields?

Because my mum wouldn't know the difference between a private key and a password and going into more details will bore her to death.

> Especially as it is possible that both are simultaneously required for a ssh login

That use case is actually supported as the password you mention is called a passphrase and that field is available

> autocomplete the password because it thinks this is a cleartext field.

Wanna create a pull request for this? I'd gladly accept a fix that don't break the current behavior entirely.

**Comment by thielepaul** [comment]
Thank you for your extensive answer!

I was not talking about a passphrase for the key but about requiring both key (with or without passphrase) and password for login (with a config like this https://security.stackexchange.com/questions/17931/possible-to-use-both-private-key-and-password-authentication-for-ssh-login).
Anyway, this is probably a rather rare configuration and I do not think that is an issue if that is not supported by filestash. It was just an example to illustrate that password and key are something different.

I believe it is not possible to fix the mobile keyboard issue while keeping a textarea as the password field.
If the only issue with using a normal input is the line break removal from ssh private keys this could be fixed in the backend using a similar logic like it is proposed here: https://stackoverflow.com/questions/56333989/convert-single-line-rsa-private-ssh-key-to-multi-line

Please let me know what you think regarding this solution. If you are fine with it, I believe I could create a pull request for it.

**Comment by thielepaul** [comment]
I created a PR (https://github.com/mickael-kerjean/filestash/pull/324) that does not break the current behaviour but fixes this issue.
Is this acceptable for you?

**Comment by mickael-kerjean** [comment]
@thielepaul PR got merged, instead of the previous hack, we now have a proper solution 👍
