### ISSUE TITLE
[Feature Request] STL File Viewer (3d models)

### ISSUE THREAD

**Issue by mwdomino** [mickael-kerjean/filestash#302]
Hey, I was looking at adding an STL Viewer plugin to render 3d printing models so I could preview them in Filestash. It appears to be pretty straightforward with some NPM packages (like `stl-viewer`) that do all the heavy lifting. My use-case for this is to provide a viewer that lets me browse my STL files stored on central storage for use between all of my printers.

If you're looking for examples, you can download any model from http://www.thingiverse.com and poke around. The mime-type is `application/octet-stream` which could be ambiguous, but we could also trigger off the file extension should you add another viewer component that responds to `octet-stream`.

I wanted to open this issue to discuss and see if you had any objections. I may need some help getting the backend to build if you're interested in this PR, as I've run into a couple issues 😄

**Comment by mickael-kerjean** [comment]
It sounds pretty good to me if you can work out a PR for this.

**Comment by subdavis** [comment]
As long as you're considering 3d model viewing, you might as well kill a few birds with one stone.

https://github.com/Kitware/F3D I think would be pretty easy to embed.

Supports...

.vtk : the legacy VTK format
.vt[p|u|r|i|s|m] : XML based VTK formats
.ply : Polygon File format
.stl : Standard Triangle Language format
.dcm : DICOM file format
.nrrd/.nhrd : "nearly raw raster data" file format
.mhd/.mha : MetaHeader MetaIO file format
.ex2/.e/.exo/.g : Exodus 2 file format
.gml : CityGML file format
.pts : Point Cloud file format
.obj : Wavefront OBJ file format (full scene)
.gltf/.glb : GL Transmission Format (full scene)
.3ds : Autodesk 3DS Max file format (full scene)
.wrl : VRML file format (full scene)

Disclaimer: This tool is made by my company, but I have no personal association with either the team or the tech that it came from.  I just noticed this issue was open and thought it'd be worth exploring.
