### ISSUE TITLE
[Feature Request] Image preview svg

### ISSUE THREAD

**Issue by darkdragon-001** [mickael-kerjean/filestash#316]
Since modern browsers support SVG vector graphics, it should be pretty much the same as for PNG.

**Comment by mickael-kerjean** [comment]
The feature is already available but disabled by default:
<img width="917" alt="Screen Shot 2020-09-30 at 11 21 32 pm" src="https://user-images.githubusercontent.com/13233076/94690650-b784fb00-0373-11eb-9cd2-93a9ab5d0c91.png">

> it should be pretty much the same as for PNG.

SVG is an entirely different beast than PNG. SVG is XML and XML can do a lot of fun stuff like XML bombs and other fun stuff that potentially crash your browser or even embed some javascript that will do anything you want. Filestash don't assume you trust the content you're connecting to and that's why it's disabled by default.

**Comment by darkdragon-001** [comment]
Should be safe to display it within `<img>`: https://security.stackexchange.com/a/177434/236907

**Comment by mickael-kerjean** [comment]
As a user you'd still be able to right click + open image in a new tab and all bets are off. That's why SVG is available but disabled by default

**Comment by darkdragon-001** [comment]
If I understand the linked discussion correctly, it's the opposite: Wrapping it inside `<img>` disables javascript, but opening the svg directly in the browser runs all the embedded javascript...

**Comment by mickael-kerjean** [comment]
The img tag by itself isn't the problem, the issue is when you right click on it and do this:
<img width="852" alt="Screen Shot 2020-10-07 at 8 11 09 pm" src="https://user-images.githubusercontent.com/13233076/95311416-50b69300-08d9-11eb-91f9-815918758353.png">

Then it's game over. Ultimately, when I went on disabling SVG by default and made it opt in,  they were a bunch of other options like sanitising the SVG but I ended up not going there as it had no intention to spend 3 months to make something rock solid that could resist any type of attack. Realistically SVG is better as an opt in feature if you know and accept the risk that comes with it

**Comment by darkdragon-001** [comment]
Clicking _Open Image in New Tab_ is basically the same as opening in attachment in an e-mail, so everybody should be aware of this anyway. Furthermore, it leads to the same result as clicking _Open Link in New Tab_ for the download link...

**Comment by mickael-kerjean** [comment]
"Clicking Open Image in New Tab" on a SVG would enable an attacker to execute javascript on the same domain you are running Filestash on. That's textbook XSS issue that would potentially leak your authentication cookie.
If that's fine to you, that's fine, the feature is already available and opt in but it will stay opt in

**Comment by darkdragon-001** [comment]
Since the same problem exhibits when clicking _Open Link in New Tab_ even with this feature disabled, I don't see a point in disabling it. And without your answer in this issue, I would think that filestash just isn't able to show svg files. Just different opinions...
