### ISSUE TITLE
Can't fork and build on docker to test

### ISSUE THREAD

**Issue by BobCashStory** [mickael-kerjean/filestash#329]
Each time you fork the repository you can't test features or fix with docker.

The docker file get the source code from a hosted zip instead of local.
A standard approach would do it locally like in this tutorial:
https://levelup.gitconnected.com/complete-guide-to-create-docker-container-for-your-golang-application-80f3fb59a15e?gi=6dd5e0216f78

**Comment by mickael-kerjean** [comment]
I know all that but there's a reason why things are the way they are today. It boils down to I don't use docker for build but as a convenience layer for distribution. As of today, it's the CI who does the build, run the tests and validate everything. The build artifacts in then uploaded to a server and pulled directly from the Dockerfile as to make the CI job much quicker to execute as it just pulls the build artifact instead of redoing an entire build again which used to be quite time consuming

**Comment by BobCashStory** [comment]
@mickael-kerjean i undertand but other solution exist "
- instead of uploading artifact the ci can do the build straight .
- artifact can be pass from one workflow to a second one
- you can do job in parallel
you have many solution who doesn't need outside server, and can help us to improve the product with you.
Even possible on github action as one of guys who forked did here : https://github.com/ServiusHack/filestash/blob/update_script/.github/workflows/update.yml
