### ISSUE TITLE
[bug] Admin page autofilling personal username and password

### ISSUE THREAD

**Issue by w0k3** [mickael-kerjean/filestash#345]
In Firefox (and maybe in other browsers) every time I open admin page, even though Username and Password was unchecked for the file back-end, it is instantly filled with my personal username + password saved on non-admin login page.

I have to remember this defect and always uncheck Username and Password to fix the configuration, which is saved in real time, so it is broken as soon as I visit the admin page. It is a security issue too - if I do not notice this effect, my username and password is saved for public access to my personal files.

I think that `autocomplete` attribute of these input fields should be `"off"` or `"new-password"`, or maybe a different username / password field name should be chosen, to prevent this situation.

A short screen recording with the problem: [Peek 2020-11-23 21-02](https://github.com/mickael-kerjean/filestash/files/5585506/Peek.2020-11-23.21-02.zip)

**Comment by mickael-kerjean** [comment]
The above commit should have fixed it, do you confirm?

**Comment by w0k3** [comment]
It looks like I can't confirm that. Even though the `autocomplete="off"` is present, somehow the Username and Password is still filled with data I never put there in the first place (it's username and password from login screen).

[Peek 2020-11-25 13-25.zip](https://github.com/mickael-kerjean/filestash/files/5604821/Peek.2020-11-25.13-25.zip)

**Comment by w0k3** [comment]
Can you try `autocomplete="new-password"` instead? It looks like the recommended solution and it seems to work...

[Peek 2020-11-26 21-12.zip](https://github.com/mickael-kerjean/filestash/files/5604841/Peek.2020-11-26.21-12.zip)

**Comment by w0k3** [comment]
:shrug:

**Comment by Bramas** [comment]
Yes the problem is still there, and @w0k3 is right, "new-password" should be used.
I made a PR to fix the issue.

**Comment by Bramas** [comment]
Hi @mickael-kerjean sorry to ping you about this again but this might be a security issue for those who allow the browser to fill automatically their password. It happened to me, my admin password was pre-filled and saved as the SFTP password in the admin, hence became accessible in the login page as well.
I can help if you need something in order to merge the fix.

Something related, when sharing with a password, the password input also should have `autocomplete="new-password"` . I can do a PR for this, but I was thinking, maybe the password when sharing should be visible, this is usually what happens when sharing something with a password in other tools (for instance rooms in zoom), and maybe when we check password, the password input should be prefilled with a short random password, because it might be the default way want to use password when sharing. What is you opinion about that, either way I can make a PR to implement this (or maybe both ways, by adding an option in the admin).
Thanks!
