### ISSUE TITLE
[bug] Able to access /admin/setup after configuration -- admin security issue

### ISSUE THREAD

**Issue by directionforward** [mickael-kerjean/filestash#394]
I am able to access the /admin/setup screen after the app has been installed and configured. And this allows me to edit the already set admin password. This seems really bad or am I missing something?!

**Comment by Bramas** [comment]
Hi, are you sure you are not connected?

**Comment by directionforward** [comment]
Hi, I was able to access on same machine but different browser.

**Comment by Bramas** [comment]
So are you sure you were not connected on the other browser ? you say "I was" because it is not working anymore or because you cannot check right now? In other word, could you reproduce it? 
In my installation I cannot access the setup page without being connected, but I could try with a fresh install if necessary.

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
