### ISSUE TITLE
[bug] not able to set S3 region

### ISSUE THREAD

**Issue by vickailiu** [mickael-kerjean/filestash#493]
# Description of the bug

not able to set S3 region

# Step by step instructions to reproduce the bug

- Click on "checkbox" before and after "Advanced"
- Copy region ("ap-southeast-1" in my case) into "region"
- When I refresh the page, the setting is not reflected to be set.

I've checked the API call: /admin/api/config after making the configuration. The post request seems does not send the "region" in the request. I've tried to add it in, but seems not working as well.

# Can you replicate that error from the demo?

# Observed behavior

# Expected behavior

**Comment by Oterem** [comment]
+1

**Comment by WGandy** [comment]
I'm running into what appears to be the same issue. I'm trying to set this up with an S3 style object storage called Garage. It requires the region be set to "garage". I set this in the advanced section and it does appear to connect to the service and create folders. But if I create a document with Filestash, I get an error when trying to save it. 
![image](https://user-images.githubusercontent.com/81717633/181606797-74cd7684-7df2-478a-9294-546c891f4b56.png)
A similar error when trying to drag a file for upload with Filestash. 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/81717633/181607093-efaf40f4-406d-4b96-9f44-15afcf705e90.png">

**Comment by mickael-kerjean** [comment]
If someone can send me a testing account I will look into it: mickael@kerjean.m

**Comment by mickael-kerjean** [comment]
I have never got any testing account to replicate this. I'm closing the ticket until somebody is willing to send me what I need to provide a fix.

**Comment by nicolasbri** [comment]
One of my users has experienced the same issue: bucketregionerror, the bucket is not in US-east-1.... code301.
He created a folder within the bucket and got the error when uploading to the folder. He could upload fine to parent folder.
I tried on my side and could upload without errors on the folder, whch makes me think it is a local issue.
After having a look on Google, user experience this issue when using Terraform (infrastructure from code) and the solution is to delete the .terraform file. 
Could there be a similar temporary file created locally by Filestash?

**Comment by mickael-kerjean** [comment]
There's temp file only whenever using things like GIT for which there's no other choices but that's not the case with S3 where there is no such temp file. To understand what's going on, I'd need to have a testing account from which I could replicate this

**Comment by nicolasbri** [comment]
Thanks for your quick response. Unfortunately I created a new bucket and a new user with permissions to S3 but cannot recreate the issue. The issue seems to be local to the user.

**Comment by lapwat** [comment]
I am currently trying out Filestash with an OVH S3 Bucket

> Commit hash     708ba9ea219e8509cc673dcfd63120573c356a71
Binary hash     46c84bed114411fac2ad1af51917e8e07d64bc749188f7cfb1e871046d92677f
Config hash     7f666a763e11e389992de3be2b5abfbe0bab1db17fe0defae2a990b0e340e150
License     AGPL
Plugins     STANDARD[plg_authenticate_admin plg_authenticate_htpasswd plg_authenticate_ldap plg_authenticate_openid plg_authenticate_passthrough plg_authenticate_saml plg_backend_artifactory plg_backend_backblaze plg_backend_dav plg_backend_dropbox plg_backend_ftp plg_backend_gdrive plg_backend_git plg_backend_ldap plg_backend_local plg_backend_mysql plg_backend_nfs plg_backend_nop plg_backend_s3 plg_backend_samba plg_backend_sftp plg_backend_storj plg_backend_tmp plg_backend_webdav plg_editor_onlyoffice plg_handler_console plg_image_ascii plg_image_c plg_image_transcode plg_search_stateless plg_security_scanner plg_security_svg plg_starter_http plg_video_transcoder]
EXTENDED[N/A]
CUSTOM[N/A]

I successfully set the Credentials in the Admin Console

> Related backend: s3
API Key
Secret Key
gra
s3.gra.io.cloud.ovh.net
Remaining fields are empty

I successfully list the buckets (appear as folder on the Filestash interface).

When I click one folder, I get this error

> Oops!
AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'gra' status code: 400, request id: tx3a34cd2a54f742aa82fb5-0066696432, host id: tx3a34cd2a54f742aa82fb5-0066696432

It seems that the region is not sent in the requests when inside a folder

The same error happens when I try to delete a folder.

**Investigation**

I remove the API key from the s3 section.

I reload the browser tab. I can still list the buckets!

I open a new Private Window in my browser: I cannot list the buckets!

It is like the s3 related backend configuration is linked to the session in the browser, how can it be ?

**Comment by Checker8763** [comment]
I have the same or similar error.

To replicate:
- Host MinIo Server
- Change the Region of MinIo Server
- Create Buckets
- Create User
- Create Application Creds for User
- Access Bucket over Filestash with Creds and custom url and region

Now the Problem, I can not create buckets.
MinIo is straight forward and gives the error expected region eu-west-1( region I set).

It seems like the region is not send with certain requests eg. Create Bucket.
