### ISSUE TITLE
[bug] Local Storage login broken

### ISSUE THREAD

**Issue by IcyMint** [mickael-kerjean/filestash#511]
# Description of the bug

When adding a local storage location and adding a password the login window is broken, not allowing to enter a password.

# Step by step instructions to reproduce the bug

- Only add a local storage option
- Set a password
- Clear cookies, hard refresh login page

# Can you replicate that error from the demo?

No, requires admin console

# Observed behavior

No field to enter a password visible

![settings_pass](https://user-images.githubusercontent.com/13654250/190295696-f143a119-62a6-4eed-b8ef-7dc78325aa44.png)
![pass_login](https://user-images.githubusercontent.com/13654250/190295704-c9707a28-979a-4848-b907-d097917f2fd3.png)

# Expected behavior

Should be able to enter a password
![settings_admin](https://user-images.githubusercontent.com/13654250/190295722-f67e0be6-22ac-49e2-8b5c-eb7856799e4c.png)
![admin_login](https://user-images.githubusercontent.com/13654250/190295735-dca7e7bb-d35b-4250-873b-040f15620738.png)

**Comment by mickael-kerjean** [comment]
I can't replicate this. Can you take a video of what you're seeing?

**Comment by IcyMint** [comment]
https://user-images.githubusercontent.com/13654250/191856946-8c358828-f040-4505-95f4-e511e9d4ea99.mp4

**Comment by telsch** [comment]
@IcyMint to answer your question where your not entered password comes from. It's stored in clear text in the server configuration.
I would expected the entered password in admin panel is the user password (bcrypt hash like the admin password) and if unchecked there is no password required at all to access the local storage.

```
--- data/config/config.json
+++ data/config/config.json
@@ -90,6 +91,7 @@
         {
             "label": "LOCAL",
             "type": "local",
+            "password": "insecure",
             "path": "/data/"
         }
     ]
```

**Comment by mickael-kerjean** [comment]
There's a whole bunch of things that should be better documented.

When you are doing this:
![image](https://user-images.githubusercontent.com/13233076/193820746-9ad8db12-14ce-49b8-be9e-5059bc37648e.png)
you are defaulting some values that are pushed to the frontend. This is to craft some login page that aren't dompting for end users like this:
![image](https://user-images.githubusercontent.com/13233076/193823047-2e0de06a-b516-421d-870c-2b54567044a3.png)

I wouldn't advise to push sensitive data in that section as it's getting push to the frontend and could easily get stolen as you saw just there:
![Screenshot from 2022-10-04 23-42-01](https://user-images.githubusercontent.com/13233076/193822029-7606e771-5913-4d43-bb32-8ab7876e7c5b.png)

If you are trying to automatically login somewhere in a safe manner, you'd need to use an anthentication middleware like [this plugin](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_authenticate_passthrough). 

so when it comes to:
![image](https://user-images.githubusercontent.com/13233076/193822518-c684cc46-7e31-4018-8bd8-336b6152e7aa.png)
yes you did exactly that at 0min43 and that is why you didn't see it back in the frontend, the idea behind this feature is simply to push some default config that aren't a secret to the world so you could craft a page that only show password or username / password or something along these lines

**Comment by mickael-kerjean** [comment]
> if unchecked

The current UX on the admin side is terrible but follow me, when something is unchecked (the default), it means the field will be displayed from the login page for the user to enter that data. When it is check, it means the field will be hidden with the default value that's configured being pushed to the frontend.

It could all be a lot better to avoid this kind of missuse, the intended use case was just to generate login page link this one:
![image](https://user-images.githubusercontent.com/13233076/193827868-3d723d94-ea01-4155-9df8-af1bab6b1081.png)


> It's stored in clear text in the server configuration.

The default is to store the entire config in the admin console in a file named config.json but you can create plugin that store that file anywhere you want with any encryption you want. For example, I know of people who have made plugin to get that config from an environment variable and other who made it available from a S3 bucket

> I would expected the entered password in admin panel is the user password (bcrypt hash like the admin password) and if unchecked there is no password required at all to access the local storage.

there might be some missunderstanding about the local plugin, I hope telling more about its history will help clear out missconceptions. When Filestash started, I didn't want to make a local plugin, the way I saw it was you could just use SFTP as a layer to access your local filesystem benefiting from the added security provided by openssh. That local plugin saw the day only  because of the demand for it. To me it was more a question of "how do we expose the local filesystem without it being a security hazard"? You wouldn't want any random dude from the internet to be able to view and change your filesystem so it was decided to put that local plugin behind the admin password so that nobody on the internet would be able to mess with it assuming you'd need the admin password to be able to do something in there.

**Comment by telsch** [comment]
Thanks for your answer.  So with passthrough middleware the password is not populated to the frontend but still in clear text in the config.json. Just wondering cause the admin password is stored as bcrypt hash. Or still misunderstood something? I don't expose this to internet and authentication is done on proxy side.
