### ISSUE TITLE
[bug] "Oops! Invalid account" when using password_only middleware for local folder

### ISSUE THREAD

**Issue by dausruddin** [mickael-kerjean/filestash#687]
# Description of the bug

I am trying to use `password_only` to allow user entering just password to access my local folder.
![image](https://github.com/mickael-kerjean/filestash/assets/5763466/aca95712-54f9-460d-8698-3386577948be)

After filling up both password and path fields, I tried to log in as the user. But was greeted with this error
![image](https://github.com/mickael-kerjean/filestash/assets/5763466/409f58a3-5b16-43c5-a7d4-95cbfd86478a)

Also something is weird. If I chose `username_and_password`, I still getting only 2 fields showing up, `Admin Password` and `Path`. I don't understand if this is how it should be or there is a mistake somewhere.
![image](https://github.com/mickael-kerjean/filestash/assets/5763466/18f068a5-ecc8-4416-b5d6-755139091016)

# Step by step instructions to reproduce the bug

1. Setup password_only as middleware to access local folder
2. Try to login as user

# Can you replicate that error from the demo?

No, since my issue is for local storage.

# Observed behavior

Greeted with error when trying to login user.

# Expected behavior

Able to view files.

**Comment by Sjoerdfc** [comment]
It took me a while to understand how everything works as well, unfortunately there is absolutely no documentation if you are not a paying customer.

I also got the 'invalid account' error a few times, and in my case the problem was that the path was not correct. In your screenshots the path is empty as well. And as far as I understand, the passthrough authentication is best used for example if you are trying to login with SSH, and you can passthrough the credentials from the login page of Filestash to SSH.

If you just want users and passwords, the htpasswd authentication is the easiest. Just don't forget to fill in your Admin password and the correct path in the two fields below under LOCAL. Also remember that if you run Filestash under docker you need to pass your storage to your docker container, and use the correct path from inside the docker container.
